app/blog/models.py
from datetime import datetime
from RealProject import db
from enum import IntEnum
from sqlalchemy.dialects.mysql import LONGTEXT


class BaseModel(db.Model):
    # 基类模型
    __abstract__ = True

    add_date = db.Column(db.DateTime, nullable=False, default=datetime.now, )  # 创建时间
    pub_date = db.Column(db.DateTime, default=datetime.now,
                         onupdate=datetime.now, nullable=False)  # 更新时间


class Category(BaseModel):
    """分类模型
    """
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False)
    icon = db.Column(db.String(128), nullable=True)

    # post = db.relationship('Post', backref='category', lazy=True)
    post = db.relationship('Post', back_populates="category", cascade="all, delete", passive_deletes=True, )

    def __repr__(self):
        return '<Category %r>' % self.name


class Tag(BaseModel):
    """ 文章标签
    """
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False, unique=True)

    def __repr__(self):
        return self.name


class PostPublishType(IntEnum):
    """ 文章发布类型
    """
    draft = 1  # 草稿
    show = 2  # 发布


# 多对多关系帮助器表
tags = db.Table('tags',
                db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'), primary_key=True),
                db.Column('post_id', db.Integer, db.ForeignKey('post.id'), primary_key=True)
                )


class Post(BaseModel):
    """ 文章
    """
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128), nullable=False)
    desc = db.Column(db.String(200), nullable=True)
    content = db.Column(LONGTEXT, nullable=False)
    has_type = db.Column(db.Enum(PostPublishType), server_default='show', nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id', ondelete="CASCADE"), nullable=False)
    # 多对多关系
    tags = db.relationship('Tag', secondary=tags,
                           lazy='subquery', backref=db.backref('post', lazy=True))
    category = db.relationship("Category", back_populates="post")

    def __repr__(self):
        return '<Post %r>' % self.title

app/admin/views.py
from ctypes import pointer
from flask import (
    Blueprint, render_template, request,
    flash, redirect, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash
from RealProject import db
from app.admin.forms import CategoryCreateForm, PostForm, TagForm, CreateUserForm
from app.admin.models import Banner
from app.admin.utils import upload_file_path
from app.auth.models.auth import User
from app.auth.views.auth import login_required
from app.blog.models import Category, Post, Tag

bp = Blueprint('admin', __name__, url_prefix='/admin',
               template_folder='templates', static_folder='static')


@bp.route('/')
@login_required
def index():
    # 主页视图
    post_count = Post.query.count()
    user_count = User.query.count()
    return render_template('admin/index.html', post_count=post_count, user_count=user_count)


@bp.route('/category')
@login_required
def category():
    # 查看分类
    page = request.args.get('page', 1, type=int)
    pagination = Category.query.order_by(-Category.add_date).paginate(page=page, per_page=10, error_out=False)
    category_list = pagination.items
    return render_template('admin/category.html', category_list=category_list, pagination=pagination)


@bp.route('/category/add', methods=['GET', 'POST'])
@login_required
def category_add():
    # 增加分类
    form = CategoryCreateForm()
    if form.validate_on_submit():
        category = Category(name=form.name.data, icon=form.icon.data)
        db.session.add(category)
        db.session.commit()
        flash(f'{form.name.data}分类添加成功')
        return redirect(url_for('admin.category'))
    return render_template('admin/category_form.html', form=form)


@bp.route('/category/edit/<int:cate_id>', methods=['GET', 'POST'])
@login_required
def category_edit(cate_id):
    # 增加分类
    category = Category.query.get(cate_id)
    form = CategoryCreateForm(name=category.name, icon=category.icon)
    if form.validate_on_submit():
        category.name = form.name.data
        category.icon = form.icon.data
        db.session.add(category)
        db.session.commit()
        flash(f'{form.name.data}分类修改成功')
        return redirect(url_for('admin.category'))
    return render_template('admin/category_form.html', form=form)


@bp.route('/category/delete/<int:cate_id>')
@login_required
def category_del(cate_id):
    cate = Category.query.get(cate_id)
    if cate:
        # 级联删除
        posts = Post.query.filter(Post.category_id == cate.id)
        print(posts.all())
        db.session.delete(cate)
        db.session.commit()
        flash(f'{cate.name}分类删除成功')
        return redirect(url_for('admin.category'))


@bp.route('/article')
@login_required
def article():
    # 查看文章列表
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(-Post.add_date).paginate(page=page, per_page=10, error_out=False)
    post_list = pagination.items
    return render_template('admin/article.html', post_list=post_list, pagination=pagination)


@bp.route('/article/add', methods=['GET', 'POST'])
@login_required
def article_add():
    # 增加文章
    form = PostForm()
    form.category_id.choices = [(v.id, v.name) for v in Category.query.all()]
    form.tags.choices = [(v.id, v.name) for v in Tag.query.all()]

    if form.validate_on_submit():
        post = Post(
            title=form.title.data,
            desc=form.desc.data,
            has_type=form.has_type.data,
            category_id=int(form.category_id.data),
            content=form.content.data,
        )
        post.tags = [Tag.query.get(tag_id) for tag_id in form.tags.data]
        db.session.add(post)
        db.session.commit()
        flash(f'{form.title.data}文章添加成功')
        return redirect(url_for('admin.article'))
    return render_template('admin/article_form.html', form=form)


@bp.route('/article/edit/<int:post_id>', methods=['GET', 'POST'])
@login_required
def article_edit(post_id):
    # 修改文章
    post = Post.query.get(post_id)
    tags = [tag.id for tag in post.tags]
    form = PostForm(
        title=post.title, desc=post.desc,
        category_id=post.category.id, has_type=post.has_type.value,
        content=post.content, tags=tags
    )

    form.category_id.choices = [(v.id, v.name) for v in Category.query.all()]
    form.tags.choices = [(v.id, v.name) for v in Tag.query.all()]

    if form.validate_on_submit():
        post.title = form.title.data
        post.desc = form.desc.data
        post.has_type = form.has_type.data
        post.category_id = int(form.category_id.data)
        post.content = form.content.data
        post.tags = [Tag.query.get(tag_id) for tag_id in form.tags.data]
        db.session.add(post)
        db.session.commit()
        flash(f'{form.title.data}文章修改成功')
        return redirect(url_for('admin.article'))
    return render_template('admin/article_form.html', form=form)


@bp.route('/article/delete/<int:post_id>', methods=['GET', 'POST'])
@login_required
def article_del(post_id):
    # 删除文章
    post = Post.query.get(post_id)
    if post:
        db.session.delete(post)
        db.session.commit()
        flash(f'{post.title}文章删除成功')
        return redirect(url_for('admin.article'))


@bp.route('/tag')
@login_required
def tag():
    # 查看标签列表
    page = request.args.get('page', 1, type=int)
    pagination = Tag.query.order_by(-Tag.add_date).paginate(page=page, per_page=10, error_out=False)
    tag_list = pagination.items
    return render_template('admin/tag.html', tag_list=tag_list, pagination=pagination)


@bp.route('/tag/add', methods=['GET', 'POST'])
@login_required
def tag_add():
    # 增加标签
    form = TagForm()
    if form.validate_on_submit():
        tag = Tag(name=form.name.data)
        db.session.add(tag)
        db.session.commit()
        flash(f'{form.name.data}添加成功')
        return redirect(url_for('admin.tag'))
    return render_template('admin/tag_form.html', form=form)


@bp.route('/tag/edit/<int:tag_id>', methods=['GET', 'POST'])
@login_required
def tag_edit(tag_id):
    # 修改标签
    tag = Tag.query.get(tag_id)
    form = TagForm(name=tag.name)
    if form.validate_on_submit():
        tag.name = form.name.data
        db.session.add(tag)
        db.session.commit()
        flash(f'{form.name.data}添加成功')
        return redirect(url_for('admin.tag'))
    return render_template('admin/tag_form.html', form=form)


@bp.route('/tag/del/<int:tag_id>', methods=['GET', 'POST'])
@login_required
def tag_del(tag_id):
    # 删除标签
    tag = Tag.query.get(tag_id)
    if tag:
        db.session.delete(tag)
        db.session.commit()
        flash(f'{tag.name}删除成功')
        return redirect(url_for('admin.tag'))


@bp.route('/user')
@login_required
def user():
    # 查看文章列表
    page = request.args.get('page', 1, type=int)
    pagination = User.query.order_by(-User.add_date).paginate(page=page, per_page=10, error_out=False)
    user_list = pagination.items
    return render_template('admin/user.html', user_list=user_list, pagination=pagination)


@bp.route('/user/add', methods=['GET', 'POST'])
@login_required
def user_add():
    # 查看文章列表
    # https://flask-wtf.readthedocs.io/en/1.0.x/form/#file-uploads
    form = CreateUserForm()
    if form.validate_on_submit():
        from .utils import upload_file_path
        f = form.avatar.data
        avatar_path, filename = upload_file_path('avatar', f)
        f.save(avatar_path)
        user = User(
            username=form.username.data,
            password=generate_password_hash(form.password.data),
            avatar=f'avatar/{filename}',
            is_super_user=form.is_super_user.data,
            is_active=form.is_active.data,
            is_staff=form.is_staff.data
        )
        db.session.add(user)
        db.session.commit()
        flash(f'{form.username.data}添加成功！')
        return redirect(url_for('admin.user'))
    return render_template('admin/user_form.html', form=form)


@bp.route('/user/edit/<int:user_id>', methods=['GET', 'POST'])
@login_required
def user_edit(user_id):
    # 修改用户信息
    user = User.query.get(user_id)

    from .utils import upload_file_path
    form = CreateUserForm(
        username=user.username,
        password=user.password,
        avatar=user.avatar,
        is_super_user=user.is_super_user,
        is_active=user.is_active,
        is_staff=user.is_staff
    )
    form.password.default = f'{user.password}'

    if form.validate_on_submit():
        user.username = form.username.data
        if not form.password.data:
            user.password = user.password
        else:
            user.password = generate_password_hash(form.password.data)
        f = form.avatar.data
        if user.avatar == f:
            user.avatar = user.avatar
        else:
            avatar_path, filename = upload_file_path('avatar', f)
            f.save(avatar_path)
            user.avatar = f'avatar/{filename}'
        user.is_super_user = form.is_super_user.data
        user.is_active = form.is_active.data
        user.is_staff = form.is_staff.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('admin.user'))
    return render_template('admin/user_form.html', form=form, user=user)


@bp.route('/user/del/<int:user_id>', methods=['GET', 'POST'])
@login_required
def user_del(user_id):
    # 删除标签
    user = User.query.get(user_id)
    if tag:
        db.session.delete(user)
        db.session.commit()
        flash(f'{user.username}删除成功')
        return redirect(url_for('admin.user'))


@bp.route('/upload', methods=['POST'])
@login_required
def upload():
    # 上传图片
    if request.method == 'POST':
        f = request.files.get('upload')
        file_size = len(f.read())

app/blog/views.py
from flask import Blueprint, render_template, request

from app.blog.models import Post, Category, Tag

bp = Blueprint('blog', __name__, url_prefix='/blog', template_folder='templates', static_folder='static')


def index():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(-Post.add_date).paginate(
        page=page, per_page=9, error_out=False)
    post_list = pagination.items

    import random
    imgs = [
        'https://scpic.chinaz.net/files/pic/pic7/xpic365.jpg',
        'https://scpic.chinaz.net/files/pic/pic6/pic1874.jpg',
        'https://scpic.chinaz.net/files/pic/pic9/201808/zzpic13908.jpg']

    for post in post_list:
        post.img = random.sample(imgs, 1)[0]

    import json
    from app.admin.models import Banner
    banners = Banner.query.all()
    banners_list = [{'img': f'/admin/static/{banner.img}', 'url': banner.url} for banner in banners]
    banners_json = json.dumps(banners_list, ensure_ascii=False)
    return render_template('index.html', posts=post_list, pagination=pagination, banners=banners_json)


@bp.route('/category/<int:cate_id>')
def cates(cate_id):
    # 分类页
    cate = Category.query.get(cate_id)
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter(Post.category_id == cate_id).paginate(page=page, per_page=10, error_out=False)
    post_list = pagination.items
    return render_template('cate_list.html', cate=cate, post_list=post_list, cate_id=cate_id, pagination=pagination)


@bp.route('/category/<int:cate_id>/<int:post_id>')
def detail(cate_id, post_id):
    # 详情页
    cate = Category.query.get(cate_id)
    post = Post.query.get_or_404(post_id)

    # 上一篇
    prev_post = Post.query.filter(Post.id < post_id).order_by(-Post.id).first()
    # 下一篇
    next_post = Post.query.filter(Post.id > post_id).order_by(Post.id).first()

    return render_template('detail.html', cate=cate, post=post, prev_post=prev_post, next_post=next_post)


@bp.context_processor
def inject_archive():
    # 文章归档日期注入上下文
    posts = Post.query.order_by(-Post.add_date)
    dates = set([post.add_date.strftime("%Y年%m月") for post in posts])
    print(dates)
    # 标签
    tags = Tag.query.all()
    for tag in tags:
        tag.style = ['is-success', 'is-danger', 'is-black', 'is-light', 'is-primary', 'is-link', 'is-info',
                     'is-warning']

    # 最新文章
    new_posts = posts.limit(6)
    return dict(dates=dates, tags=tags, new_posts=new_posts)


@bp.route('/search')
def search():
    # 搜索视图
    words = request.args.get('words', '', type=str)
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter(Post.title.like("%" + words + "%")).paginate(page=page, per_page=10, error_out=False)
    post_list = pagination.items
    return render_template('search.html', post_list=post_list, words=words, pagination=pagination)


@bp.route('/category/<string:date>')
def archive(date):
    # 归档页
    import re
    # 正则匹配年月
    regex = re.compile(r'\d{4}|\d{2}')
    dates = regex.findall(date)

    from sqlalchemy import extract, and_, or_
    page = request.args.get('page', 1, type=int)
    # 根据年月获取数据
    archive_posts = Post.query.filter(
        and_(extract('year', Post.add_date) == int(dates[0]), extract('month', Post.add_date) == int(dates[1])))
    # 对数据进行分页
    pagination = archive_posts.paginate(page=page, per_page=10, error_out=False)
    return render_template('archive.html', post_list=pagination.items, pagination=pagination, date=date)


@bp.route('/tags/<int:tag_id>')
def tags(tag_id):
    # 标签页
    tag = Tag.query.get(tag_id)
    return render_template('tags.html', post_list=tag.post, tag=tag)

app/blog/templates/base.html
<!DOCTYPE html>
<html lang="cn">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{{ url_for('blog.static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('blog.static', filename='css/buefy.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('blog.static', filename='css/materialdesignicons.min.css') }}">
    {% block extra_head_style %}{% endblock extra_head_style %}
</head>

<body>
    <div id="app" style="height:100%;">
        <div class="container is-fluid1" style="height:100%; ">
            <div class="is-block" style="height:100%;">
                <!-- 导航 -->
                {% block navbar %}
                <template>
                    <b-navbar spaced shadow>
                        <template #brand>
                            <b-navbar-item>
                                <img src="{{ url_for('blog.static', filename='img/logo.png') }}" alt="FlaskBlog">
                            </b-navbar-item>
                        </template>
                        <template #start>
                            <b-navbar-item href="/"
                                {% if request.path =='/' %}active {% endif %}>
                                首页
                            </b-navbar-item>

                            <!-- 查询菜单数据 -->
                            {% for cate in categorys %}
                                <b-navbar-item
                                    {% if cate.id == cate_id %}class="has-text-primary"{% endif %}
                                    href="{{ url_for('blog.cates', cate_id=cate.id) }}">
                                    {{ cate.name }}
                                </b-navbar-item>
                            {% endfor %}
                        </template>

                        <template #end>
                            <b-navbar-item tag="div">
                                <!-- 判断用户是否已登录 -->
                                {% if g.user %}
                                <div class=" buttons">
                                    <!-- 获取用户信息 -->
                                    <a class="button is-primary">欢迎您 {{ g.user['username'] }}</a>
                                    {% if g.user.is_super_user %}
                                        <a class="button is-success" href="{{ url_for('admin.index') }}">管理后台</a>
                                    {% else %}
                                        <a class="button is-success" href="{{ url_for('auth.userinfo') }}">个人中心</a>
                                    {% endif %}
                                    <!-- 显示推出按钮 -->
                                    <a class="button is-danger" href="{{ url_for('auth.logout') }}">退出</a>
                                </div>
                                {% else %}
                                <!-- 用户未登录，显示登录注册按钮 -->
                                <div class="buttons">
                                    <a class="button is-primary" href="{{ url_for('auth.register') }}">
                                        <strong>Sign up</strong>
                                    </a>
                                    <a class="button is-light" href="{{ url_for('auth.login') }}">Log in</a>
                                </div>
                                {% endif %}
                            </b-navbar-item>
                        </template>
                    </b-navbar>
                </template>
                {% endblock navbar %}
                <!-- 导航 end -->

                {% block hero %}
                <section class="hero is-medium is-primary">
                    <div class="hero-body">
                        <p class="title">
                            Large hero
                        </p>
                        <p class="subtitle">
                            Large subtitle
                        </p>
                    </div>
                </section>
                {% endblock hero %}

                {% block main %} 
                <div class="box is-marginless is-shadowless is-radiusless">
                    {% block box %}
                    <div class="columns is-multiline">
                        {% for post in posts %}
                        <div class="column is-4-fullhd is-6-desk">
                            <div class="card">
                                <div class="card-image">
                                    <figure class="image is-4by5">
                                        <img src="{{ post.img }}" alt="Placeholder image">
                                    </figure>
                                </div>
                                <div class="card-content">
                                    <div class="content">
                                        <p class="title is-4"><a
                                                href="{{ url_for('blog.detail', cate_id=post.category.id, post_id=post.id) }}">
                                            {{ post.title}}</a> </p>
                                        <p class="has-text-grey subtitle is-size-6">
                                            {{ post.desc }}
                                        </p>
                                        <time class="has-text-grey" datetime="{{ post.add_date }}">{{ post.add_date }}</time>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                    <nav class="pagination is-small" role="navigation" aria-label="pagination">
                    {% if pagination.has_prev %}
                    <a href="{{ url_for('admin.article') }}?page={{ pagination.prev_num }}" class="pagination-previous" title="This is the first page">上一页</a>
                    {% endif %}
                    {% if pagination.has_next %}
                    <a href="{{ url_for('admin.article') }}?page={{ pagination.next_num }}" class="pagination-next">下一页</a>
                    {% endif %}

                    <ul class="pagination-list">
                        {% for page in pagination.iter_pages() %}
                            {% if page %}
                                {% if page != pagination.page %}
                                <li>
                                    <a href="{{ url_for('admin.article') }}?page={{ page }}" class="pagination-link" aria-label="Page 1" aria-current="page">{{ page }}</a>
                                </li>
                                {% else %}
                                <li>
                                    <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">{{ page }}</a>
                                </li>
                                {% endif %}
                            {% else %}
                                <span class=pagination-ellipsis>&hellip;</span>
                            {% endif %}
                        {% endfor %}

                    </ul>
                </nav>
                    {% endblock box %}
                </div>
                {% endblock main %}



                {% block footer %}      
                <div class="footer has-background-black-ter is-marginless">
                    <div class="has-text-centered has-text-grey-light">
                        © 2022 <a class="has-text-grey-light" href="http://127.0.0.1/">FlaskBlog博客开发</a> 版权所有 备案号：xxxxx
                    </div>
                </div>
                {% endblock footer %}
            </div>

        </div>
    </div>

    <script src="{{ url_for('blog.static', filename='js/vue.js') }}"></script>
    <script src="{{ url_for('blog.static', filename='js/buefy.min.js') }}"></script>
    {% block extra_foot_script %}{% endblock extra_foot_script %}
    <script>
        var app = new Vue({
            el: '#app',
            delimiters: ['{$', '$}'],
            data: {
                file:{},
                carousels:[],
                banners: []
            },
            methods: {}
        })
    </script>
    {% block vue_script %}{% endblock vue_script %}
</body>

</html>

app/blog/templates/cate_list.html
{% extends 'base.html' %}

{% block title %}{{ cate.name }}{% endblock title %}

{% block hero %}{% endblock hero %}

{% block box %}
<div class="columns">
    <div class="column is-9" style="border-right:solid 1px #eee ;">
        <div class="box is-shadowless has-background-light">
            {% block breadcrumb %}
            <nav class="breadcrumb is-small" aria-label="breadcrumbs">
                <ul>
                <li><a href="/">首页</a></li>
                <li class="is-active"><a href="#" aria-current="page">{{ cate.name }}</a></li>
                </ul>
            </nav>
            {% endblock breadcrumb %}
        </div>

        {% block cate_box %}
        {% for post in post_list %}
            <div class="pl-2">
                <h1 class="is-size-4">
                    <a href="{{ url_for('blog.detail', cate_id=post.category.id, post_id=post.id) }}">{{ post.title }}</a>
                </h1>
                <p class="has-text-grey-light is-size-6 mt-1">
                    <span class="icon"><i class="mdi mdi-clipboard-text-clock-outline"></i></span>{{ post.add_date }}
                    <span class="icon"><i class="mdi mdi-shape-outline"></i></span>{{ post.category.name }}
                    <span class="icon"><i class="mdi mdi-tag-heart-outline"></i></span>{{ post.tags|join(',') }}
                </p>
                <div class="has-text-grey mt-1">{{ post.desc }}</div>
            </div>
            <div class=" dropdown-divider mb-3"></div>
        {% endfor %}
        {% block pagination %}
        <nav class="pagination is-small" role="navigation" aria-label="pagination">
            {% if pagination.has_prev %}
            <a href="{{ url_for('blog.cates', cate_id=cate.id ) }}?page={{ pagination.prev_num }}" class="pagination-previous" title="This is the first page">Previous</a>
            {% endif %}
            {% if pagination.has_next %}
            <a href="{{ url_for('blog.cates', cate_id=cate.id) }}?page={{ pagination.next_num }}" class="pagination-next">Next page</a>
            {% endif %}

            <ul class="pagination-list">
                {% for page in pagination.iter_pages() %}
                    {% if page %}
                        {% if page != pagination.page %}
                        <li>
                            <a href="{{ url_for('blog.cates', cate_id=cate.id) }}?page={{ page }}" class="pagination-link" aria-label="Page 1" aria-current="page">{{ page }}</a>
                        </li>
                        {% else %}
                        <li>
                            <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">{{ page }}</a>
                        </li>
                        {% endif %}
                    {% else %}
                        <span class=pagination-ellipsis>&hellip;</span>
                    {% endif %}
                {% endfor %}

            </ul>
        </nav>
        {% endblock pagination %}
        {% endblock cate_box %}
    </div>

    <div class="box is-shadowless" style="border:solid 1px #eee ;">
        <!--搜索-->
        <h1 class="is-size-6 icon-text">
            <span class="icon"><i class="mdi mdi-search-web"></i></span>
            搜索
        </h1>
        <div class=" dropdown-divider"></div>
        <form action="{{ url_for('blog.search') }}" method="get">
            <div class="field has-addons">
                <div class="control">
                <input class="input" type="search" value="{{ words }}" name="words" placeholder="请输入关键字">
                </div>
                <div class="control">
                <input type="submit" value="Search" class="button is-info">
                </div>
            </div>
        </form>

        <!--归档-->
        <h1 class="is-size-6 icon-text">
            <span class="icon"><i class="mdi mdi-calendar-month-outline"></i></span>
            归档
        </h1>
        <div class=" dropdown-divider"></div>
        <ul>
            {% for date in dates %}
            <li class="pl-2"><a href="{{ url_for('blog.archive', date=date) }}">{{ date }}</a></li>
            <div class="dropdown-divider"></div>
            {% endfor %}
        </ul>

        <!--最新文章-->
        <h1 class="is-size-6 icon-text">
        <span class="icon"><i class="mdi mdi-calendar-month-outline"></i></span>
        最新文章
    </h1>
        <div class=" dropdown-divider"></div>
        <ul>
        {% for post in new_posts %}
        <li class="pl-2">
            <span class=" has-text-grey-light">{{ loop.index }}.</span>
            <a href="{{ url_for('blog.detail', cate_id=post.category.id, post_id=post.id) }}">{{ post.title }}</a>
        </li>
        <div class="dropdown-divider"></div>
        {% endfor %}
    </ul>
                <!--标签-->
        <h1 class="is-size-6 icon-text">
            <span class="icon"><i class="mdi mdi-tag-multiple-outline"></i></span>
            标签
        </h1>
        <div class=" dropdown-divider"></div>
        <div class="tags">
                {% for tag in tags %}
                <a class="tag {{ tag.style|random() }}" href="{{ url_for('blog.tags', tag_id=tag.id) }}">{{ tag.name }}</a>
                {% endfor %}
            </div>

    </div>
</div>
{% endblock box %}

app/blog/templates/detail.html
{% extends 'cate_list.html' %}

{% block title %}
    {{ post.title }}
{% endblock title %}

{% block breadcrumb %}
    <nav class="breadcrumb is-small" aria-label="breadcrumbs">
        <ul>
            <li><a href="/">首页</a></li>
            <li><a href="{{ url_for('blog.cates', cate_id=cate.id) }}">{{ cate.name }}</a></li>
            <li class="is-active"><a href="#" aria-current="page">{{ post.title }}</a></li>
        </ul>
    </nav>
{% endblock breadcrumb %}

{% block cate_box %}
<div class="pl-2">
    <h1 class="is-size-3">
        {{ post.title }}
    </h1>
    <p class="has-text-grey-light is-size-6 mt-1">
        <span class="icon"><i class="mdi mdi-clipboard-text-clock-outline"></i></span>{{ post.add_date }}
        <span class="icon"><i class="mdi mdi-shape-outline"></i></span>{{ post.category.name }}
        <span class="icon"><i class="mdi mdi-tag-heart-outline"></i></span>{{ post.tags|join(',') }}
    </p>
    <div class="content has-text-grey mt-1">{{ post.content|safe }}</div>
</div>

<hr>
<div class="level">
    <div class="level-left">
        {% if prev_post %}
            上一篇：<a href="{{ url_for('blog.detail', cate_id=prev_post.category.id, post_id=prev_post.id) }}">{{ prev_post.title }}</a>
        {% endif %}
    </div>
    <div class="level-right">
        {% if next_post %}
            下一篇：<a href="{{ url_for('blog.detail', cate_id=next_post.category.id, post_id=next_post.id) }}">{{ next_post.title }}</a>
        {% endif %}
    </div>
</div>
{% endblock cate_box %}